### ISSUE TITLE
Generate go_* rules without third_party dependencies

### ISSUE THREAD

**Issue by sagikazarmark** [tcncloud/wollemi#4]
I'm trying to introduce Please to our projects at Banzai Cloud. Sadly, the modules support of Please is not perfect yet, so I decided to take an iterative approach and embrace the incremental build features in small steps.

I got to a point where I have custom `go_library`, `go_binary` and `go_test` targets that rely on the go build tool and build cache. This is good enough until go modules support is mature enough to use.

I wrote a custom tool to generate the initial `go_library` and `go_test` rules, but I'd love to use wollemi instead. The only thing that keeps me from doing it right now is that it complains about the missing third party dependencies.

It would be nice to have a way to disable the resolution of third-party dependencies entirely, so that wollemi can focus only on the packages inside the project.

I know this is somewhat controversial as it's not the "Please way", but I think the iterative process of introducing Please to a project is the right path as it can deliver value early compared to spending weeks on migrating the entire build process. Having support for that in wollemi would be cool.

What do you think? Having spent some time with Go list and packages recently, it doesn't feel like a large change.

**Comment by brian-bice** [comment]
@sagikazarmark How does your custom go rules provide the dependencies that the wollemi tool is complaining about being missing?

**Comment by sagikazarmark** [comment]
They are loaded from GOPATH, downloaded by `go mod download` separately. Basically, they use a global GOPATH.

**Comment by brian-bice** [comment]
But I would assume that still must be provided into your custom go rules in some way. Is that happening through a deps field or by some other means?

```
custom_go_library(
    name = "foo",
    srcs = glob(["*.go"]),
    deps = [
        "//gopath",
    ],
)
```

**Comment by sagikazarmark** [comment]
No, I manually provide a gopath to the environment which then uses the downloaded modules from there. It's not perfect, certainly not 100% hermetic, but works fine.

**Comment by brian-bice** [comment]
If I am understanding correctly you still want wollemi to add internal dependencies to your rules. i.e. other `go_library` rules while not adding the `go_get` rules since you are handling those yourself through the gopath. Is that correct?

Assuming that is the case we could just add an `allow_unresolved_dependency` config setting which would prevent the tool from skipping the rule generation step where unresolved dependencies were detected. This would make it generate the rule with internal dependencies but without the third party dependencies which it could not find. Would this be sufficient for what you are looking for?

**Comment by sagikazarmark** [comment]
Yes, that sounds exactly what I'm looking for!

**Comment by brian-bice** [comment]
Wollemi should now behave as described above when the `allow_unresolved_dependency` config field is set to true.

**Comment by sagikazarmark** [comment]
Just tried it: works perfectly. Funny thing: it didn't actually touch any of my current rules. I manually modified a few of them and ran wollemi again: it reverted the changes. So I guess it works fine.

Thanks!

**Comment by brian-bice** [comment]
@sagikazarmark Great. Glad to hear it.

That behavior is by design to provide more flexibility. Some fields are not modified on pre-existing rules. For example, `visibility` is never altered on pre-existing rules so that it can be changed by hand and future runs of wollemi continue to work without destroying the manual changes. Also, for another example, wollemi generally generates the `srcs` field for `go_library` rules  as `glob(["*.go", exclude = ["*_test.go"])`. However if you manually change an existing rules `srcs` field to be an explicit list of files instead then future runs of wollemi will leave that change in place and will instead sync the code dependencies based on that explicit list of files. This makes it possible have separate please `go_library` and `go_test` rules, if that's something so desired, while still being able to leverage wollemi to keep the please `deps` in sync with the actual code for each hand modified rule.

In general wollemi attempts to generate what you don't have and work with what you do have rather than force you to have what it thinks you should have.

**Comment by sagikazarmark** [comment]
> That behavior is by design to provide more flexibility.

I rather meant that my generated BUILD files matched the buildifier style and resolved the correct dependencies. Wollemi didn't changes those...because they were already what they should have been, so I could just replace my own tool with wollemi. 🙂 

> In general wollemi attempts to generate what you don't have and work with what you do have rather than force you to have what it thinks you should have.

That's why I actually wanted to use wollemi, because my tool just generated a static set of targets, instead of working with the existing ones. I really like how wollemi works. 👍
