### ISSUE TITLE
Running wollemi from please

### ISSUE THREAD

**Issue by sagikazarmark** [tcncloud/wollemi#7]
Installation instructions for a please rule have been removed here: https://github.com/tcncloud/wollemi/commit/b344d6a6871393696c510df33c4f45b069a166a6

The commit message references an issue, but I couldn't find any more details about it.

What is that issue exactly? It's be nice to add that installation method back.

**Comment by sagikazarmark** [comment]
@brian-bice I'm working on our internal tooling and would like to integrate wollemi into it using please aliases. Can you help me figure out how to do that? Thanks!

**Comment by namtzigla** [comment]
@sagikazarmark we will add back that in the readme

**Comment by brian-bice** [comment]
@sagikazarmark Sorry, it would have been much better had I defined what the actual issue was in the commit message.

The wollemi binary needs to know the GOROOT path to be able to distinguish external imports from GOROOT imports. In the case of the build rule, and the downloaded binary, I think the GOROOT essentially gets set to empty string which is wrong. This makes wollemi think that stdlib imports like `database/sql` are actually external imports and unable to resolve them. At the time I wasn't sure how to fix this in a generalized way which is why I temporarily removed it from the README.

I might be able to dig back into this issue over the weekend but probably not sooner. But maybe this is something you already know how to fix? It may just be a matter of defining that build rule differently?

@sagikazarmark What is a please alias? I don't think I have heard that terminology before. Could help me to understand what those are or point me to some documentation which explains those?

**Comment by sagikazarmark** [comment]
Ah, okay, I guess that can be worked around.

Alias as defined here: https://please.build/config.html

Basically I want to give the devs a command like `plz wollemi` to run wollemi in a project.

**Comment by sagikazarmark** [comment]
The following snippet will create a shell script that sets GOROOT to the one used by please:

``` starlark
build_rule(
    name = "wollemi",
    outs = ["wollemi.sh"],
    binary = True,
    cmd = "cat > \"$OUT\" << EOF\n#!/bin/sh\nexport GOROOT=$(\"$TOOLS_GO\" env GOROOT)\n$(out_exe :wollemi-binary) \\\\$@\nEOF\n",
    tools = {"go": [CONFIG.GO_TOOL]},
    visibility = ["PUBLIC"],
    deps = [":wollemi-binary"],
)
```

Output:

```
#!/bin/sh
export GOROOT=/usr/local/Cellar/go/1.15.2/libexec
plz-out/bin/wollemi $@
```

**Comment by Tatskaari** [comment]
The go root is no longer set automatically in all build rules. I felt it was a bit odd because please isn't specifically a go build system. The go binaries don't really need that variable to figure out where the go root is most of the time. I think something like above makes sense :)

**Comment by sagikazarmark** [comment]
The advantage of the above script is that it works with `go_toolchain` as well. (compared to just using `go`)
